# Generated by Django 3.2.2 on 2024-11-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0009_alter_complaint_type_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='Type_of_questions',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('1', 'What career options are available based on my strengths and interests?'), ('0', 'What are the essential skills required for success in specific fields or industries?'), ('2', 'How do I choose the right stream (Science, Commerce, or Arts) for my future career goals?'), ('3', 'What is the current job market like for fresh graduates, and which industries have the best job prospects?'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
